### ISSUE TITLE
Final website fixes

### ISSUE THREAD

**Issue by luisramalho** [futurice/vor#69]
**Task (Priority)**
- [x] right top menu centered (2)
- [x] center the banner on the header (2)
- [x] icons even smaller, 1/3 smaller and closer to text (5)
- [x] "Who we are" same style as the other section (4)
- [x] increase header margin-bottom on Our sponsors & futurice (4)
- [x] all buttons same size, read fixed width (4)
- [x] add wireframe to the services page (4)
- [x] fixed the social media icons, they should be round (5)

Each commit should fix an issue, please reference this issue in each commit. High priority fixes first.

**Comment by luisramalho** [comment]
All the issues are solved!
